version: '3.4'

services:
  tp1apigateway:
    image: ${DOCKER_REGISTRY-}tp1apigateway
    build:
      context: .
      dockerfile: Tp1ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    networks:
      my_network:
       ipv4_address: 172.16.238.10

  tp1usercontrollmanager:
    image: ${DOCKER_REGISTRY-}tp1usercontrollmanager
    build:
      context: .
      dockerfile: Tp1UserControllManager/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
    ports:
      - "8000"
    networks:
      - my_network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin123456"
      ACCEPT_EULA: "Y"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
